#pragma once

#define SERIAL_USART_HALF_DUPLEX
#define SERIAL_USART_TX_PIN GP1
#define EE_HANDS
#define SPLIT_WATCHDOG_TIMEOUT 300000
#define UNICODE_SELECTED_MODES UNICODE_MODE_LINUX, UNICODE_MODE_WINCOMPOSE
